spring:
  datasource:
    url: ${AWS_RDS_JIKCHON}
    driverClassName: com.mysql.cj.jdbc.Driver
    username: ${RDS_USERNAME}
    password: ${RDS_PASSWORD}
  jpa:
    database-platform: org.hibernate.dialect.MySQL8Dialect
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
        show_sql: true
        format_sql: true
        default_batch_fetch_size: 200
    hibernate:
      ddl-auto: update



server:
  port: 8080
  error:
    whitelabel:
      enabled: false



jwt:
  secret-key:
    access: ${JWT-ACCESS-TOKEN-SECRET-KEY}
    refresh: ${JWT-REFRESH-TOKEN-SECRET-KEY}